### PR TITLE
Quick addition of Opera support

### PR DESCRIPTION
**Pull request by BadOPCode**
This is nothing too fancy.  Just duplicating Chrome extension and adding necessary changes for Opera. NEX packed it and have been testing it.  Chrome extensions are not automatically available in Opera.  In my opinion, Opera should be made as a new target in project.  As it has it's own extension store and extension system even though it's compatible with Chrome.

### CODE REVIEW

**Comment by mgabdev** [comment]
Hi @BadOPCode, thanks for submitting a PR. In the `config/browsers.js` file I see you duplicated the chrome configuration as you mentioned. You also mentioned you've added necessary changes for Opera; did you make these directly to any files within the `build/` directory?

**Comment by BadOPCode** [comment]
No.  At least not in this PR.  I wasn't sure if you wanted the NEX packed file and pem in the build so I left them out. In the future there probably will be.  I believe I saw some style differences on what I am using in Opera and what is in Chrome.

**Comment by BadOPCode** [comment]
☝️ Based on what I've seen in screen shots from people using Dissenter.

**Comment by BadOPCode** [comment]
dissenter

@mgabdev This is what it looks like in Opera right now.

**Comment by BadOPCode** [comment]
PR is too preemptive.  The goal of the PR was to target the API differences https://dev.opera.com/extensions/apis/
But also to separate Opera and Chrome packed files from each other so that a Opera Store submission could be made.  (Obviously not in my place to handle.)
After thinking about it, I'm probably jumping the gun on this as the extension is still in the early stages.  I'm closing this PR but will maintain my fork with Opera as a target until a PR makes more sense. IE when there is a Opera specific bug or feature.

**Pull request closed without merging**
